int A = 2;  
 int B = 3;
 int C = 4;
 int D = 5;
 int E = 6;
 int F = 7;
 int G = 8;
 int H = 9;
 int I = 10;
 int J = 11;    
 int K = 12;  
 int L = A5;
 int M = A4;
 int N = A3;
 int P = A2;
 int Q = A1;
 int R = A0;
 int S = 13;
 int d = 1000;
 int d1 = 5;
void setup() {              
 pinMode(A, OUTPUT);  
 pinMode(B, OUTPUT);
 pinMode(C, OUTPUT);
 pinMode(D, OUTPUT);
 pinMode(E, OUTPUT);
 pinMode(F, OUTPUT);
 pinMode(G, OUTPUT);
 pinMode(H, OUTPUT);
 pinMode(I, OUTPUT);
 pinMode(J, OUTPUT);    
 pinMode(K, OUTPUT);  
 pinMode(L, OUTPUT);
 pinMode(M, OUTPUT);
 pinMode(N, OUTPUT);
 pinMode(P, OUTPUT);
 pinMode(Q, OUTPUT);
 pinMode(R, OUTPUT);
 pinMode(S, OUTPUT);
}
void loop(){
//1
digitalWrite(A, HIGH);
delay(d);
//2
digitalWrite(A, HIGH);  
digitalWrite(B, HIGH);
delay(d);
//3
digitalWrite(A, HIGH);  
digitalWrite(B, HIGH);
digitalWrite(C, HIGH);
delay(d);
//4
digitalWrite(A, HIGH);  
digitalWrite(B, HIGH);
digitalWrite(C, HIGH);
digitalWrite(D, HIGH);
delay(d);
//5
digitalWrite(A, HIGH);  
digitalWrite(B, HIGH);
digitalWrite(C, HIGH);
digitalWrite(D, HIGH);
digitalWrite(E, HIGH);
delay(d);
//6
digitalWrite(A, HIGH);  
digitalWrite(B, HIGH);
digitalWrite(C, HIGH);
digitalWrite(D, HIGH);
digitalWrite(E, HIGH);
digitalWrite(F, HIGH);
delay(d);
//7
digitalWrite(A, HIGH);  
digitalWrite(B, HIGH);
digitalWrite(C, HIGH);
digitalWrite(D, HIGH);
digitalWrite(E, HIGH);
digitalWrite(F, HIGH);
digitalWrite(G, HIGH);
delay(d);
//8
digitalWrite(A, HIGH);  
digitalWrite(B, HIGH);
digitalWrite(C, HIGH);
digitalWrite(D, HIGH);
digitalWrite(E, HIGH);
digitalWrite(F, HIGH);
digitalWrite(G, HIGH);
digitalWrite(H, HIGH);
delay(d);
//9
digitalWrite(A, HIGH);  
digitalWrite(B, HIGH);
digitalWrite(C, HIGH);
digitalWrite(D, HIGH);
digitalWrite(E, HIGH);
digitalWrite(F, HIGH);
digitalWrite(G, HIGH);
digitalWrite(H, HIGH);
digitalWrite(I, HIGH);
delay(d);
digitalWrite(A, LOW);  
digitalWrite(B, LOW);
digitalWrite(C, LOW);
digitalWrite(D, LOW);
digitalWrite(E, LOW);
digitalWrite(F, LOW);
digitalWrite(G, LOW);
digitalWrite(H, LOW);
digitalWrite(I, LOW);
delay(d1);
//10
digitalWrite(J, HIGH);
delay(d);
//11
digitalWrite(A, HIGH);
digitalWrite(J, HIGH);  
delay(d);
//12
digitalWrite(A, HIGH);  
digitalWrite(B, HIGH);
digitalWrite(J, HIGH);  
delay(d);
//13
digitalWrite(A, HIGH);  
digitalWrite(B, HIGH);
digitalWrite(C, HIGH);
digitalWrite(J, HIGH);  
delay(d);
//14
digitalWrite(A, HIGH);  
digitalWrite(B, HIGH);
digitalWrite(C, HIGH);
digitalWrite(D, HIGH);
digitalWrite(J, HIGH);  
delay(d);
//15
digitalWrite(A, HIGH);  
digitalWrite(B, HIGH);
digitalWrite(C, HIGH);
digitalWrite(D, HIGH);
digitalWrite(E, HIGH);
digitalWrite(J, HIGH);  
delay(d);
//16
digitalWrite(A, HIGH);  
digitalWrite(B, HIGH);
digitalWrite(C, HIGH);
digitalWrite(D, HIGH);
digitalWrite(E, HIGH);
digitalWrite(F, HIGH);
digitalWrite(J, HIGH);  
delay(d);
//17
digitalWrite(A, HIGH);  
digitalWrite(B, HIGH);
digitalWrite(C, HIGH);
digitalWrite(D, HIGH);
digitalWrite(E, HIGH);
digitalWrite(F, HIGH);
digitalWrite(G, HIGH);
digitalWrite(J, HIGH);  
delay(d);
//18
digitalWrite(A, HIGH);  
digitalWrite(B, HIGH);
digitalWrite(C, HIGH);
digitalWrite(D, HIGH);
digitalWrite(E, HIGH);
digitalWrite(F, HIGH);
digitalWrite(G, HIGH);
digitalWrite(H, HIGH);
digitalWrite(J, HIGH);  
delay(d);
//19
digitalWrite(A, HIGH);  
digitalWrite(B, HIGH);
digitalWrite(C, HIGH);
digitalWrite(D, HIGH);
digitalWrite(E, HIGH);
digitalWrite(F, HIGH);
digitalWrite(G, HIGH);
digitalWrite(H, HIGH);
digitalWrite(I, HIGH);
digitalWrite(J, HIGH);  
delay(d);
digitalWrite(A, LOW);  
digitalWrite(B, LOW);
digitalWrite(C, LOW);
digitalWrite(D, LOW);
digitalWrite(E, LOW);
digitalWrite(F, LOW);
digitalWrite(G, LOW);
digitalWrite(H, LOW);
digitalWrite(I, LOW);
digitalWrite(J, LOW);
delay(d1);
//20
digitalWrite(J, HIGH);  
digitalWrite(K, HIGH);
delay(d);
//21
digitalWrite(A, HIGH);
digitalWrite(J, HIGH);  
digitalWrite(K, HIGH);
delay(d);
//22
digitalWrite(A, HIGH);  
digitalWrite(B, HIGH);
digitalWrite(J, HIGH);  
digitalWrite(K, HIGH);
delay(d);
//23
digitalWrite(A, HIGH);  
digitalWrite(B, HIGH);
digitalWrite(C, HIGH);
digitalWrite(J, HIGH);  
digitalWrite(K, HIGH);
delay(d);
//24
digitalWrite(A, HIGH);  
digitalWrite(B, HIGH);
digitalWrite(C, HIGH);
digitalWrite(D, HIGH);
digitalWrite(J, HIGH);  
digitalWrite(K, HIGH);
delay(d);
//25
digitalWrite(A, HIGH);  
digitalWrite(B, HIGH);
digitalWrite(C, HIGH);
digitalWrite(D, HIGH);
digitalWrite(E, HIGH);
digitalWrite(J, HIGH);  
digitalWrite(K, HIGH);
delay(d);
//26
digitalWrite(A, HIGH);  
digitalWrite(B, HIGH);
digitalWrite(C, HIGH);
digitalWrite(D, HIGH);
digitalWrite(E, HIGH);
digitalWrite(F, HIGH);
digitalWrite(J, HIGH);  
digitalWrite(K, HIGH);
delay(d);
//27
digitalWrite(A, HIGH);  
digitalWrite(B, HIGH);
digitalWrite(C, HIGH);
digitalWrite(D, HIGH);
digitalWrite(E, HIGH);
digitalWrite(F, HIGH);
digitalWrite(G, HIGH);
digitalWrite(J, HIGH);  
digitalWrite(K, HIGH);
delay(d);
//28
digitalWrite(A, HIGH);  
digitalWrite(B, HIGH);
digitalWrite(C, HIGH);
digitalWrite(D, HIGH);
digitalWrite(E, HIGH);
digitalWrite(F, HIGH);
digitalWrite(G, HIGH);
digitalWrite(H, HIGH);;
digitalWrite(J, HIGH);  
digitalWrite(K, HIGH);
delay(d);
//29
digitalWrite(A, HIGH);  
digitalWrite(B, HIGH);
digitalWrite(C, HIGH);
digitalWrite(D, HIGH);
digitalWrite(E, HIGH);
digitalWrite(F, HIGH);
digitalWrite(G, HIGH);
digitalWrite(H, HIGH);
digitalWrite(I, HIGH);
digitalWrite(J, HIGH);  
digitalWrite(K, HIGH);
delay(d);
digitalWrite(A, LOW);  
digitalWrite(B, LOW);
digitalWrite(C, LOW);
digitalWrite(D, LOW);
digitalWrite(E, LOW);
digitalWrite(F, LOW);
digitalWrite(G, LOW);
digitalWrite(H, LOW);
digitalWrite(I, LOW);
digitalWrite(J, LOW);
digitalWrite(K, LOW);
delay(d1);
//30
digitalWrite(J, HIGH);  
digitalWrite(K, HIGH);
digitalWrite(L, HIGH);
delay(d);
//31
digitalWrite(A, HIGH);
digitalWrite(J, HIGH);  
digitalWrite(K, HIGH);
digitalWrite(L, HIGH);
delay(d);
//32
digitalWrite(A, HIGH);  
digitalWrite(B, HIGH);
digitalWrite(J, HIGH);  
digitalWrite(K, HIGH);
digitalWrite(L, HIGH);
delay(d);
//33
digitalWrite(A, HIGH);  
digitalWrite(B, HIGH);
digitalWrite(C, HIGH);
digitalWrite(J, HIGH);  
digitalWrite(K, HIGH);
digitalWrite(L, HIGH);
delay(d);
//34
digitalWrite(A, HIGH);  
digitalWrite(B, HIGH);
digitalWrite(C, HIGH);
digitalWrite(D, HIGH);
digitalWrite(J, HIGH);  
digitalWrite(K, HIGH);
digitalWrite(L, HIGH);
delay(d);
//35
digitalWrite(A, HIGH);  
digitalWrite(B, HIGH);
digitalWrite(C, HIGH);
digitalWrite(D, HIGH);
digitalWrite(E, HIGH);
digitalWrite(J, HIGH);  
digitalWrite(K, HIGH);
digitalWrite(L, HIGH);
delay(d);
//36
digitalWrite(A, HIGH);  
digitalWrite(B, HIGH);
digitalWrite(C, HIGH);
digitalWrite(D, HIGH);
digitalWrite(E, HIGH);
digitalWrite(F, HIGH);
digitalWrite(J, HIGH);  
digitalWrite(K, HIGH);
digitalWrite(L, HIGH);
delay(d);
//37
digitalWrite(A, HIGH);  
digitalWrite(B, HIGH);
digitalWrite(C, HIGH);
digitalWrite(D, HIGH);
digitalWrite(E, HIGH);
digitalWrite(F, HIGH);
digitalWrite(G, HIGH);
digitalWrite(J, HIGH);  
digitalWrite(K, HIGH);
digitalWrite(L, HIGH);
delay(d);
//38
digitalWrite(A, HIGH);  
digitalWrite(B, HIGH);
digitalWrite(C, HIGH);
digitalWrite(D, HIGH);
digitalWrite(E, HIGH);
digitalWrite(F, HIGH);
digitalWrite(G, HIGH);
digitalWrite(H, HIGH);
digitalWrite(J, HIGH);  
digitalWrite(K, HIGH);
digitalWrite(L, HIGH);
delay(d);
//39
digitalWrite(A, HIGH);  
digitalWrite(B, HIGH);
digitalWrite(C, HIGH);
digitalWrite(D, HIGH);
digitalWrite(E, HIGH);
digitalWrite(F, HIGH);
digitalWrite(G, HIGH);
digitalWrite(H, HIGH);
digitalWrite(I, HIGH);
digitalWrite(J, HIGH);  
digitalWrite(K, HIGH);
digitalWrite(L, HIGH);
delay(d);
digitalWrite(A, LOW);  
digitalWrite(B, LOW);
digitalWrite(C, LOW);
digitalWrite(D, LOW);
digitalWrite(E, LOW);
digitalWrite(F, LOW);
digitalWrite(G, LOW);
digitalWrite(H, LOW);
digitalWrite(I, LOW);
digitalWrite(J, LOW);
digitalWrite(K, LOW);
digitalWrite(L, LOW);
delay(d1);
//40
digitalWrite(J, HIGH);  
digitalWrite(K, HIGH);
digitalWrite(L, HIGH);
digitalWrite(M, HIGH);
delay(d);
//41
digitalWrite(A, HIGH);
digitalWrite(J, HIGH);  
digitalWrite(K, HIGH);
digitalWrite(L, HIGH);
digitalWrite(M, HIGH);
delay(d);
//42
digitalWrite(A, HIGH);
digitalWrite(B, HIGH);
digitalWrite(J, HIGH);  
digitalWrite(K, HIGH);
digitalWrite(L, HIGH);
digitalWrite(M, HIGH);
delay(d);
//43
digitalWrite(A, HIGH);
digitalWrite(B, HIGH);
digitalWrite(C, HIGH);
digitalWrite(J, HIGH);  
digitalWrite(K, HIGH);
digitalWrite(L, HIGH);
digitalWrite(M, HIGH);
delay(d);
//44
digitalWrite(A, HIGH);
digitalWrite(B, HIGH);
digitalWrite(C, HIGH);
digitalWrite(D, HIGH);
digitalWrite(J, HIGH);  
digitalWrite(K, HIGH);
digitalWrite(L, HIGH);
digitalWrite(M, HIGH);
delay(d);
//45
digitalWrite(A, HIGH);
digitalWrite(B, HIGH);
digitalWrite(C, HIGH);
digitalWrite(D, HIGH);
digitalWrite(E, HIGH);
digitalWrite(J, HIGH);  
digitalWrite(K, HIGH);
digitalWrite(L, HIGH);
digitalWrite(M, HIGH);
delay(d);
//46
digitalWrite(A, HIGH);
digitalWrite(B, HIGH);
digitalWrite(C, HIGH);
digitalWrite(D, HIGH);
digitalWrite(E, HIGH);
digitalWrite(F, HIGH);
digitalWrite(J, HIGH);  
digitalWrite(K, HIGH);
digitalWrite(L, HIGH);
digitalWrite(M, HIGH);
delay(d);
//47
digitalWrite(A, HIGH);
digitalWrite(B, HIGH);
digitalWrite(C, HIGH);
digitalWrite(D, HIGH);
digitalWrite(E, HIGH);
digitalWrite(F, HIGH);
digitalWrite(G, HIGH);
digitalWrite(J, HIGH);  
digitalWrite(K, HIGH);
digitalWrite(L, HIGH);
digitalWrite(M, HIGH);
delay(d);
//48
digitalWrite(A, HIGH);
digitalWrite(B, HIGH);
digitalWrite(C, HIGH);
digitalWrite(D, HIGH);
digitalWrite(E, HIGH);
digitalWrite(F, HIGH);
digitalWrite(G, HIGH);
digitalWrite(H, HIGH);;
digitalWrite(J, HIGH);  
digitalWrite(K, HIGH);
digitalWrite(L, HIGH);
digitalWrite(M, HIGH);
delay(d);
//49
digitalWrite(A, HIGH);
digitalWrite(B, HIGH);
digitalWrite(C, HIGH);
digitalWrite(D, HIGH);
digitalWrite(E, HIGH);
digitalWrite(F, HIGH);
digitalWrite(G, HIGH);
digitalWrite(H, HIGH);
digitalWrite(I, HIGH);
digitalWrite(J, HIGH);  
digitalWrite(K, HIGH);
digitalWrite(L, HIGH);
digitalWrite(M, HIGH);
delay(d);
digitalWrite(A, LOW);  
digitalWrite(B, LOW);
digitalWrite(C, LOW);
digitalWrite(D, LOW);
digitalWrite(E, LOW);
digitalWrite(F, LOW);
digitalWrite(G, LOW);
digitalWrite(H, LOW);
digitalWrite(I, LOW);
digitalWrite(J, LOW);
digitalWrite(K, LOW);
digitalWrite(L, LOW);
digitalWrite(M, LOW);
delay(d1);
//50  
digitalWrite(J, HIGH);  
digitalWrite(K, HIGH);
digitalWrite(L, HIGH);
digitalWrite(M, HIGH);
digitalWrite(N, HIGH);
delay(d);
//51
digitalWrite(A, HIGH);
digitalWrite(J, HIGH);  
digitalWrite(K, HIGH);
digitalWrite(L, HIGH);
digitalWrite(M, HIGH);
digitalWrite(N, HIGH);
delay(d);
//52
digitalWrite(A, HIGH);
digitalWrite(B, HIGH);
digitalWrite(J, HIGH);  
digitalWrite(K, HIGH);
digitalWrite(L, HIGH);
digitalWrite(M, HIGH);
digitalWrite(N, HIGH);
delay(d);
//53
digitalWrite(A, HIGH);
digitalWrite(B, HIGH);
digitalWrite(C, HIGH);
digitalWrite(J, HIGH);  
digitalWrite(K, HIGH);
digitalWrite(L, HIGH);
digitalWrite(M, HIGH);
digitalWrite(N, HIGH);
delay(d);
//54
digitalWrite(A, HIGH);
digitalWrite(B, HIGH);
digitalWrite(C, HIGH);
digitalWrite(D, HIGH);
digitalWrite(J, HIGH);  
digitalWrite(K, HIGH);
digitalWrite(L, HIGH);
digitalWrite(M, HIGH);
digitalWrite(N, HIGH);
delay(d);
//55
digitalWrite(A, HIGH);
digitalWrite(B, HIGH);
digitalWrite(C, HIGH);
digitalWrite(D, HIGH);
digitalWrite(E, HIGH);
digitalWrite(J, HIGH);  
digitalWrite(K, HIGH);
digitalWrite(L, HIGH);
digitalWrite(M, HIGH);
digitalWrite(N, HIGH);
delay(d);
//56
digitalWrite(A, HIGH);
digitalWrite(B, HIGH);
digitalWrite(C, HIGH);
digitalWrite(D, HIGH);
digitalWrite(E, HIGH);
digitalWrite(F, HIGH);
digitalWrite(J, HIGH);  
digitalWrite(K, HIGH);
digitalWrite(L, HIGH);
digitalWrite(M, HIGH);
digitalWrite(N, HIGH);
delay(d);
//57
digitalWrite(A, HIGH);
digitalWrite(B, HIGH);
digitalWrite(C, HIGH);
digitalWrite(D, HIGH);
digitalWrite(E, HIGH);
digitalWrite(F, HIGH);
digitalWrite(G, HIGH);
digitalWrite(J, HIGH);  
digitalWrite(K, HIGH);
digitalWrite(L, HIGH);
digitalWrite(M, HIGH);
digitalWrite(N, HIGH);
delay(d);
//58
digitalWrite(A, HIGH);
digitalWrite(B, HIGH);
digitalWrite(C, HIGH);
digitalWrite(D, HIGH);
digitalWrite(E, HIGH);
digitalWrite(F, HIGH);
digitalWrite(G, HIGH);
digitalWrite(H, HIGH);
digitalWrite(J, HIGH);  
digitalWrite(K, HIGH);
digitalWrite(L, HIGH);
digitalWrite(M, HIGH);
digitalWrite(N, HIGH);
delay(d);
//59
digitalWrite(A, HIGH);
digitalWrite(B, HIGH);
digitalWrite(C, HIGH);
digitalWrite(D, HIGH);
digitalWrite(E, HIGH);
digitalWrite(F, HIGH);
digitalWrite(G, HIGH);
digitalWrite(H, HIGH);
digitalWrite(I, HIGH);
digitalWrite(J, HIGH);  
digitalWrite(K, HIGH);
digitalWrite(L, HIGH);
digitalWrite(M, HIGH);
digitalWrite(N, HIGH);
delay(d);
digitalWrite(A, LOW);  
digitalWrite(B, LOW);
digitalWrite(C, LOW);
digitalWrite(D, LOW);
digitalWrite(E, LOW);
digitalWrite(F, LOW);
digitalWrite(G, LOW);
digitalWrite(H, LOW);
digitalWrite(I, LOW);
digitalWrite(J, LOW);
digitalWrite(K, LOW);
digitalWrite(L, LOW);
digitalWrite(M, LOW);
digitalWrite(N, LOW);
delay(d1);
//60  
digitalWrite(J, HIGH);  
digitalWrite(K, HIGH);
digitalWrite(L, HIGH);
digitalWrite(M, HIGH);
digitalWrite(N, HIGH);
digitalWrite(P, HIGH);
delay(d);
//61
digitalWrite(A, HIGH);
digitalWrite(J, HIGH);  
digitalWrite(K, HIGH);
digitalWrite(L, HIGH);
digitalWrite(M, HIGH);
digitalWrite(N, HIGH);
digitalWrite(P, HIGH);
delay(d);
//62
digitalWrite(A, HIGH);
digitalWrite(B, HIGH);
digitalWrite(J, HIGH);  
digitalWrite(K, HIGH);
digitalWrite(L, HIGH);
digitalWrite(M, HIGH);
digitalWrite(N, HIGH);
digitalWrite(P, HIGH);
delay(d);
//63
digitalWrite(A, HIGH);
digitalWrite(B, HIGH);
digitalWrite(C, HIGH);
digitalWrite(J, HIGH);  
digitalWrite(K, HIGH);
digitalWrite(L, HIGH);
digitalWrite(M, HIGH);
digitalWrite(N, HIGH);
digitalWrite(P, HIGH);
delay(d);
//64
digitalWrite(A, HIGH);
digitalWrite(B, HIGH);
digitalWrite(C, HIGH);
digitalWrite(D, HIGH);
digitalWrite(J, HIGH);  
digitalWrite(K, HIGH);
digitalWrite(L, HIGH);
digitalWrite(M, HIGH);
digitalWrite(N, HIGH);
digitalWrite(P, HIGH);
delay(d);
//65
digitalWrite(A, HIGH);
digitalWrite(B, HIGH);
digitalWrite(C, HIGH);
digitalWrite(D, HIGH);
digitalWrite(E, HIGH);
digitalWrite(J, HIGH);  
digitalWrite(K, HIGH);
digitalWrite(L, HIGH);
digitalWrite(M, HIGH);
digitalWrite(N, HIGH);
digitalWrite(P, HIGH);
delay(d);
//66
digitalWrite(A, HIGH);
digitalWrite(B, HIGH);
digitalWrite(C, HIGH);
digitalWrite(D, HIGH);
digitalWrite(E, HIGH);
digitalWrite(F, HIGH);
digitalWrite(J, HIGH);  
digitalWrite(K, HIGH);
digitalWrite(L, HIGH);
digitalWrite(M, HIGH);
digitalWrite(N, HIGH);
digitalWrite(P, HIGH);
delay(d);
//67
digitalWrite(A, HIGH);
digitalWrite(B, HIGH);
digitalWrite(C, HIGH);
digitalWrite(D, HIGH);
digitalWrite(E, HIGH);
digitalWrite(F, HIGH);
digitalWrite(G, HIGH);
digitalWrite(J, HIGH);  
digitalWrite(K, HIGH);
digitalWrite(L, HIGH);
digitalWrite(M, HIGH);
digitalWrite(N, HIGH);
digitalWrite(P, HIGH);
delay(d);
//68
digitalWrite(A, HIGH);
digitalWrite(B, HIGH);
digitalWrite(C, HIGH);
digitalWrite(D, HIGH);
digitalWrite(E, HIGH);
digitalWrite(F, HIGH);
digitalWrite(G, HIGH);
digitalWrite(H, HIGH);
digitalWrite(J, HIGH);  
digitalWrite(K, HIGH);
digitalWrite(L, HIGH);
digitalWrite(M, HIGH);
digitalWrite(N, HIGH);
digitalWrite(P, HIGH);
delay(d);
//69
digitalWrite(A, HIGH);
digitalWrite(B, HIGH);
digitalWrite(C, HIGH);
digitalWrite(D, HIGH);
digitalWrite(E, HIGH);
digitalWrite(F, HIGH);
digitalWrite(G, HIGH);
digitalWrite(H, HIGH);
digitalWrite(I, HIGH);
digitalWrite(J, HIGH);  
digitalWrite(K, HIGH);
digitalWrite(L, HIGH);
digitalWrite(M, HIGH);
digitalWrite(N, HIGH);
digitalWrite(P, HIGH);
delay(d);
digitalWrite(A, LOW);  
digitalWrite(B, LOW);
digitalWrite(C, LOW);
digitalWrite(D, LOW);
digitalWrite(E, LOW);
digitalWrite(F, LOW);
digitalWrite(G, LOW);
digitalWrite(H, LOW);
digitalWrite(I, LOW);
digitalWrite(J, LOW);
digitalWrite(K, LOW);
digitalWrite(L, LOW);
digitalWrite(M, LOW);
digitalWrite(N, LOW);
digitalWrite(P, LOW);
delay(d1);
//70  
digitalWrite(J, HIGH);  
digitalWrite(K, HIGH);
digitalWrite(L, HIGH);
digitalWrite(M, HIGH);
digitalWrite(N, HIGH);
digitalWrite(P, HIGH);
digitalWrite(Q, HIGH);
delay(d);
//71
digitalWrite(A, HIGH);
digitalWrite(J, HIGH);  
digitalWrite(K, HIGH);
digitalWrite(L, HIGH);
digitalWrite(M, HIGH);
digitalWrite(N, HIGH);
digitalWrite(P, HIGH);
digitalWrite(Q, HIGH);
delay(d);
//72
digitalWrite(A, HIGH);
digitalWrite(B, HIGH);
digitalWrite(J, HIGH);  
digitalWrite(K, HIGH);
digitalWrite(L, HIGH);
digitalWrite(M, HIGH);
digitalWrite(N, HIGH);
digitalWrite(P, HIGH);
digitalWrite(Q, HIGH);
delay(d);
//73
digitalWrite(A, HIGH);
digitalWrite(B, HIGH);
digitalWrite(C, HIGH);
digitalWrite(J, HIGH);  
digitalWrite(K, HIGH);
digitalWrite(L, HIGH);
digitalWrite(M, HIGH);
digitalWrite(N, HIGH);
digitalWrite(P, HIGH);
digitalWrite(Q, HIGH);
delay(d);
//74
digitalWrite(A, HIGH);
digitalWrite(B, HIGH);
digitalWrite(C, HIGH);
digitalWrite(D, HIGH);
digitalWrite(J, HIGH);  
digitalWrite(K, HIGH);
digitalWrite(L, HIGH);
digitalWrite(M, HIGH);
digitalWrite(N, HIGH);
digitalWrite(P, HIGH);
digitalWrite(Q, HIGH);
delay(d);
//75
digitalWrite(A, HIGH);
digitalWrite(B, HIGH);
digitalWrite(C, HIGH);
digitalWrite(D, HIGH);
digitalWrite(E, HIGH);
digitalWrite(J, HIGH);  
digitalWrite(K, HIGH);
digitalWrite(L, HIGH);
digitalWrite(M, HIGH);
digitalWrite(N, HIGH);
digitalWrite(P, HIGH);
digitalWrite(Q, HIGH);
delay(d);
//76
digitalWrite(A, HIGH);
digitalWrite(B, HIGH);
digitalWrite(C, HIGH);
digitalWrite(D, HIGH);
digitalWrite(E, HIGH);
digitalWrite(F, HIGH);
digitalWrite(J, HIGH);  
digitalWrite(K, HIGH);
digitalWrite(L, HIGH);
digitalWrite(M, HIGH);
digitalWrite(N, HIGH);
digitalWrite(P, HIGH);
digitalWrite(Q, HIGH);
delay(d);
//77
digitalWrite(A, HIGH);
digitalWrite(B, HIGH);
digitalWrite(C, HIGH);
digitalWrite(D, HIGH);
digitalWrite(E, HIGH);
digitalWrite(F, HIGH);
digitalWrite(G, HIGH);
digitalWrite(J, HIGH);  
digitalWrite(K, HIGH);
digitalWrite(L, HIGH);
digitalWrite(M, HIGH);
digitalWrite(N, HIGH);
digitalWrite(P, HIGH);
digitalWrite(Q, HIGH);
delay(d);
//78
digitalWrite(A, HIGH);
digitalWrite(B, HIGH);
digitalWrite(C, HIGH);
digitalWrite(D, HIGH);
digitalWrite(E, HIGH);
digitalWrite(F, HIGH);
digitalWrite(G, HIGH);
digitalWrite(H, HIGH);
digitalWrite(J, HIGH);  
digitalWrite(K, HIGH);
digitalWrite(L, HIGH);
digitalWrite(M, HIGH);
digitalWrite(N, HIGH);
digitalWrite(P, HIGH);
digitalWrite(Q, HIGH);
delay(d);
//79
digitalWrite(A, HIGH);
digitalWrite(B, HIGH);
digitalWrite(C, HIGH);
digitalWrite(D, HIGH);
digitalWrite(E, HIGH);
digitalWrite(F, HIGH);
digitalWrite(G, HIGH);
digitalWrite(H, HIGH);
digitalWrite(I, HIGH);
digitalWrite(J, HIGH);  
digitalWrite(K, HIGH);
digitalWrite(L, HIGH);
digitalWrite(M, HIGH);
digitalWrite(N, HIGH);
digitalWrite(P, HIGH);
digitalWrite(Q, HIGH);
delay(d);
digitalWrite(A, LOW);  
digitalWrite(B, LOW);
digitalWrite(C, LOW);
digitalWrite(D, LOW);
digitalWrite(E, LOW);
digitalWrite(F, LOW);
digitalWrite(G, LOW);
digitalWrite(H, LOW);
digitalWrite(I, LOW);
digitalWrite(J, LOW);
digitalWrite(K, LOW);
digitalWrite(L, LOW);
digitalWrite(M, LOW);
digitalWrite(N, LOW);
digitalWrite(P, LOW);
digitalWrite(Q, LOW);
delay(d1);
//80
digitalWrite(J, HIGH);  
digitalWrite(K, HIGH);
digitalWrite(L, HIGH);
digitalWrite(M, HIGH);
digitalWrite(N, HIGH);
digitalWrite(P, HIGH);
digitalWrite(Q, HIGH);
digitalWrite(R, HIGH);
delay(d);
//81
digitalWrite(A, HIGH);
digitalWrite(J, HIGH);  
digitalWrite(K, HIGH);
digitalWrite(L, HIGH);
digitalWrite(M, HIGH);
digitalWrite(N, HIGH);
digitalWrite(P, HIGH);
digitalWrite(Q, HIGH);
digitalWrite(R, HIGH);
delay(d);
//82
digitalWrite(A, HIGH);
digitalWrite(B, HIGH);
digitalWrite(J, HIGH);  
digitalWrite(K, HIGH);
digitalWrite(L, HIGH);
digitalWrite(M, HIGH);
digitalWrite(N, HIGH);
digitalWrite(P, HIGH);
digitalWrite(Q, HIGH);
digitalWrite(R, HIGH);
delay(d);
//83
digitalWrite(A, HIGH);
digitalWrite(B, HIGH);
digitalWrite(C, HIGH);
digitalWrite(J, HIGH);  
digitalWrite(K, HIGH);
digitalWrite(L, HIGH);
digitalWrite(M, HIGH);
digitalWrite(N, HIGH);
digitalWrite(P, HIGH);
digitalWrite(Q, HIGH);
digitalWrite(R, HIGH);
delay(d);
//84
digitalWrite(A, HIGH);
digitalWrite(B, HIGH);
digitalWrite(C, HIGH);
digitalWrite(D, HIGH);
digitalWrite(J, HIGH);  
digitalWrite(K, HIGH);
digitalWrite(L, HIGH);
digitalWrite(M, HIGH);
digitalWrite(N, HIGH);
digitalWrite(P, HIGH);
digitalWrite(Q, HIGH);
digitalWrite(R, HIGH);
delay(d);
//85
digitalWrite(A, HIGH);
digitalWrite(B, HIGH);
digitalWrite(C, HIGH);
digitalWrite(D, HIGH);
digitalWrite(E, HIGH);
digitalWrite(J, HIGH);  
digitalWrite(K, HIGH);
digitalWrite(L, HIGH);
digitalWrite(M, HIGH);
digitalWrite(N, HIGH);
digitalWrite(P, HIGH);
digitalWrite(Q, HIGH);
digitalWrite(R, HIGH);
delay(d);
//86
digitalWrite(A, HIGH);
digitalWrite(B, HIGH);
digitalWrite(C, HIGH);
digitalWrite(D, HIGH);
digitalWrite(E, HIGH);
digitalWrite(F, HIGH);
digitalWrite(J, HIGH);  
digitalWrite(K, HIGH);
digitalWrite(L, HIGH);
digitalWrite(M, HIGH);
digitalWrite(N, HIGH);
digitalWrite(P, HIGH);
digitalWrite(Q, HIGH);
digitalWrite(R, HIGH);
delay(d);
//87
digitalWrite(A, HIGH);
digitalWrite(B, HIGH);
digitalWrite(C, HIGH);
digitalWrite(D, HIGH);
digitalWrite(E, HIGH);
digitalWrite(F, HIGH);
digitalWrite(G, HIGH);
digitalWrite(J, HIGH);  
digitalWrite(K, HIGH);
digitalWrite(L, HIGH);
digitalWrite(M, HIGH);
digitalWrite(N, HIGH);
digitalWrite(P, HIGH);
digitalWrite(Q, HIGH);
digitalWrite(R, HIGH);
delay(d);
//88
digitalWrite(A, HIGH);
digitalWrite(B, HIGH);
digitalWrite(C, HIGH);
digitalWrite(D, HIGH);
digitalWrite(E, HIGH);
digitalWrite(F, HIGH);
digitalWrite(G, HIGH);
digitalWrite(H, HIGH);
digitalWrite(J, HIGH);  
digitalWrite(K, HIGH);
digitalWrite(L, HIGH);
digitalWrite(M, HIGH);
digitalWrite(N, HIGH);
digitalWrite(P, HIGH);
digitalWrite(Q, HIGH);
digitalWrite(R, HIGH);
delay(d);
//89
digitalWrite(A, HIGH);
digitalWrite(B, HIGH);
digitalWrite(C, HIGH);
digitalWrite(D, HIGH);
digitalWrite(E, HIGH);
digitalWrite(F, HIGH);
digitalWrite(G, HIGH);
digitalWrite(H, HIGH);
digitalWrite(I, HIGH);
digitalWrite(J, HIGH);  
digitalWrite(K, HIGH);
digitalWrite(L, HIGH);
digitalWrite(M, HIGH);
digitalWrite(N, HIGH);
digitalWrite(P, HIGH);
digitalWrite(Q, HIGH);
digitalWrite(R, HIGH);
delay(d);
digitalWrite(A, LOW);  
digitalWrite(B, LOW);
digitalWrite(C, LOW);
digitalWrite(D, LOW);
digitalWrite(E, LOW);
digitalWrite(F, LOW);
digitalWrite(G, LOW);
digitalWrite(H, LOW);
digitalWrite(I, LOW);
digitalWrite(J, LOW);
digitalWrite(K, LOW);
digitalWrite(L, LOW);
digitalWrite(M, LOW);
digitalWrite(N, LOW);
digitalWrite(P, LOW);
digitalWrite(Q, LOW);
digitalWrite(R, LOW);
delay(d1);
//90  
digitalWrite(J, HIGH);  
digitalWrite(K, HIGH);
digitalWrite(L, HIGH);
digitalWrite(M, HIGH);
digitalWrite(N, HIGH);
digitalWrite(P, HIGH);
digitalWrite(Q, HIGH);
digitalWrite(R, HIGH);
digitalWrite(S, HIGH);
delay(d);
//91
digitalWrite(A, HIGH);
digitalWrite(J, HIGH);  
digitalWrite(K, HIGH);
digitalWrite(L, HIGH);
digitalWrite(M, HIGH);
digitalWrite(N, HIGH);
digitalWrite(P, HIGH);  
digitalWrite(Q, HIGH);
digitalWrite(R, HIGH);
digitalWrite(S, HIGH);
delay(d);
//92
digitalWrite(A, HIGH);
digitalWrite(B, HIGH);
digitalWrite(J, HIGH);  
digitalWrite(K, HIGH);
digitalWrite(L, HIGH);
digitalWrite(M, HIGH);
digitalWrite(N, HIGH);
digitalWrite(P, HIGH);  
digitalWrite(Q, HIGH);
digitalWrite(R, HIGH);
digitalWrite(S, HIGH);
delay(d);
//93
digitalWrite(A, HIGH);
digitalWrite(B, HIGH);
digitalWrite(C, HIGH);
digitalWrite(J, HIGH);  
digitalWrite(K, HIGH);
digitalWrite(L, HIGH);
digitalWrite(M, HIGH);
digitalWrite(N, HIGH);
digitalWrite(P, HIGH);  
digitalWrite(Q, HIGH);
digitalWrite(R, HIGH);
digitalWrite(S, HIGH);
delay(d);
//94
digitalWrite(A, HIGH);
digitalWrite(B, HIGH);
digitalWrite(C, HIGH);
digitalWrite(D, HIGH);
digitalWrite(J, HIGH);  
digitalWrite(K, HIGH);
digitalWrite(L, HIGH);
digitalWrite(M, HIGH);
digitalWrite(N, HIGH);
digitalWrite(P, HIGH);  
digitalWrite(Q, HIGH);
digitalWrite(R, HIGH);
digitalWrite(S, HIGH);
delay(d);
//95
digitalWrite(A, HIGH);
digitalWrite(B, HIGH);
digitalWrite(C, HIGH);
digitalWrite(D, HIGH);
digitalWrite(E, HIGH);
digitalWrite(J, HIGH);  
digitalWrite(K, HIGH);
digitalWrite(L, HIGH);
digitalWrite(M, HIGH);
digitalWrite(N, HIGH);
digitalWrite(P, HIGH);  
digitalWrite(Q, HIGH);
digitalWrite(R, HIGH);
digitalWrite(S, HIGH);
delay(d);
//96
digitalWrite(A, HIGH);
digitalWrite(B, HIGH);
digitalWrite(C, HIGH);
digitalWrite(D, HIGH);
digitalWrite(E, HIGH);
digitalWrite(F, HIGH);
digitalWrite(J, HIGH);  
digitalWrite(K, HIGH);
digitalWrite(L, HIGH);
digitalWrite(M, HIGH);
digitalWrite(N, HIGH);
digitalWrite(P, HIGH);  
digitalWrite(Q, HIGH);
digitalWrite(R, HIGH);
digitalWrite(S, HIGH);
delay(d);
//97
digitalWrite(A, HIGH);
digitalWrite(B, HIGH);
digitalWrite(C, HIGH);
digitalWrite(D, HIGH);
digitalWrite(E, HIGH);
digitalWrite(F, HIGH);
digitalWrite(G, HIGH);
digitalWrite(J, HIGH);  
digitalWrite(K, HIGH);
digitalWrite(L, HIGH);
digitalWrite(M, HIGH);
digitalWrite(N, HIGH);
digitalWrite(P, HIGH);  
digitalWrite(Q, HIGH);
digitalWrite(R, HIGH);
digitalWrite(S, HIGH);
delay(d);
//98
digitalWrite(A, HIGH);
digitalWrite(B, HIGH);
digitalWrite(C, HIGH);
digitalWrite(D, HIGH);
digitalWrite(E, HIGH);
digitalWrite(F, HIGH);
digitalWrite(G, HIGH);
digitalWrite(H, HIGH);
digitalWrite(J, HIGH);  
digitalWrite(K, HIGH);
digitalWrite(L, HIGH);
digitalWrite(M, HIGH);
digitalWrite(N, HIGH);
digitalWrite(P, HIGH);  
digitalWrite(Q, HIGH);
digitalWrite(R, HIGH);
digitalWrite(S, HIGH);
delay(d);
//99
digitalWrite(A, HIGH);
digitalWrite(B, HIGH);
digitalWrite(C, HIGH);
digitalWrite(D, HIGH);
digitalWrite(E, HIGH);
digitalWrite(F, HIGH);
digitalWrite(G, HIGH);
digitalWrite(H, HIGH);
digitalWrite(I, HIGH);
digitalWrite(J, HIGH);  
digitalWrite(K, HIGH);
digitalWrite(L, HIGH);
digitalWrite(M, HIGH);
digitalWrite(N, HIGH);
digitalWrite(P, HIGH);  
digitalWrite(Q, HIGH);
digitalWrite(R, HIGH);
digitalWrite(S, HIGH);
delay(d);
digitalWrite(A, LOW);  
digitalWrite(B, LOW);
digitalWrite(C, LOW);
digitalWrite(D, LOW);
digitalWrite(E, LOW);
digitalWrite(F, LOW);
digitalWrite(G, LOW);
digitalWrite(H, LOW);
digitalWrite(I, LOW);
digitalWrite(J, LOW);
digitalWrite(K, LOW);
digitalWrite(L, LOW);
digitalWrite(M, LOW);
digitalWrite(N, LOW);
digitalWrite(P, LOW);
digitalWrite(Q, LOW);
digitalWrite(R, LOW);
digitalWrite(S, LOW);
delay(d1);
}
